### ISSUE TITLE
Syntax Error: Expecting a literal type

### ISSUE THREAD

**Issue by RainerWinkler** [StephanEggermont/MorphicDraw#3]
I try to install Morphic Draw on Pharo5. I get always a syntax error: "Expecting a literal type2:

oppositeCorners
	^Dictionary newFromPairs:#Expecting a literal type ->  (topLeft bottomRight: 
	leftCenter rightCenter: 
	bottomLeft topRight: 
	bottomCenter topCenter:
	bottomRight topLeft: 
	rightCenter leftCenter:
	topRight bottomLeft:
	topCenter bottomCenter:)

What I can I do to load

**Comment by StephanEggermont** [comment]
Thanks Rainer. I updated the Configuration, should load now.

**Comment by RainerWinkler** [comment]
Hi Stephan,
I still have the error. I followed the instruction on Github on Pharo 5:
"Open the Monticello Browser. Add a new repository of type smalltalkhub.com. The owner is StephanEggermont, the project is MorphicDraw."

There is a different explanation on the Pharo catalog (http://catalog.pharo.org/catalog/project/MorphicDraw?_s=okUZkDdCL5TgGJ0n&_k=6_CBTVzbW1aM8k1-)
I call the Metacello script and have the same error:
Metacello new
	smalltalkhubUser: 'Pharo' project: 'MetaRepoForPharo50';
	configuration: 'MorphicDraw';
	version: #stable;
	load.
I also tried to load this Monticello repository mentioned in the Pharo catalog:
MCSmalltalkhubRepository 
	owner: 'Pharo' 
	project: 'MetaRepoForPharo50'
	user: ''
	password: ''
I click on the uppermost entry "ConfigurationOfXMLParser-monty.353.mcz (!) and load. There is no error, but MorphicDraw open. is not working (As I expected as the load was very fast).

**Comment by StephanEggermont** [comment]
You might to need to clean your monticello package cache or load the newer version of ConfigurationOfMorphicDraw by hand

**Comment by RainerWinkler** [comment]
I never worked with configuration files in Monticello. I finaly did the following:
1. Load the latest ConfigurationOfMorphicDraw in Monticello.
2. Executed "ConfigurationOfMorphicDraw load." in the Playground.
Now I can load. Thank you :-)
